services:
  backend:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app

  frontend:
    build: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    environment:
      BACKEND_BASE_URL: "http://backend:8000"
      NEXTAUTH_URL: "http://localhost:3000/"
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      NODE_ENV: "development"