name: CI Pipeline

# When to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# What jobs to run
jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      working-directory: ./fastapi
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Run basic syntax check
    - name: Check Python syntax
      working-directory: ./fastapi
      run: |
        python -m py_compile main.py
        python -m py_compile functions.py
    
    # Step 5: Test Docker build
    - name: Test Docker build
      working-directory: ./fastapi
      run: |
        docker build -t test-fastapi .
        echo "Docker build successful!"